name = "zuowenai"
main = "worker.js"
compatibility_date = "2026-03-12"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "zuowen.zhinijianli.cn", custom_domain = true }
]

[assets]
directory = "public"
binding = "ASSETS"

[vars]
OPENAI_BASE_URL = "https://api.linapi.net/v1"
OPENAI_MODEL = "gemini-3-flash-preview"
